import { Injectable } from '@angular/core';
import { LoaiMuBaoHiemResponse } from './loai-mu-bao-hiem-api.service';
import { SanPhamResponse } from './product-api.service';

@Injectable({
  providedIn: 'root'
})
export class MockDataService {
  
  getMockCategories(): LoaiMuBaoHiemResponse[] {
    return [
      {
        id: 1,
        tenLoai: 'Nón 3/4',
        moTa: 'Mũ bảo hiểm 3/4 che phủ phần đầu và tai',
        trangThai: true
      },
      {
        id: 2,
        tenLoai: 'Nón Full Face',
        moTa: 'Mũ bảo hiểm full face che toàn bộ đầu và mặt',
        trangThai: true
      },
      {
        id: 3,
        tenLoai: 'Nón lật cằm',
        moTa: 'Mũ bảo hiểm modular có thể lật phần cằm',
        trangThai: true
      },
      {
        id: 4,
        tenLoai: 'Nón trẻ em',
        moTa: 'Mũ bảo hiểm dành cho trẻ em',
        trangThai: true
      },
      {
        id: 5,
        tenLoai: 'Nón Carbon',
        moTa: 'Mũ bảo hiểm làm từ chất liệu carbon cao cấp',
        trangThai: true
      },
      {
        id: 6,
        tenLoai: 'Phụ kiện',
        moTa: 'Các phụ kiện cho mũ bảo hiểm',
        trangThai: true
      }
    ];
  }

  getMockProducts(): SanPhamResponse[] {
    return [
      {
        id: 1,
        tenSanPham: 'Royal H1 Full Face',
        maSanPham: 'ROYAL-H1',
        giaBan: 840000,
        soLuongTon: 50,
        moTa: 'Mũ bảo hiểm full face cao cấp',
        trangThai: true,
        ngayTao: new Date().toISOString(),
        anhSanPham: '/assets/default-product.png',
        loaiMuBaoHiemId: 2,
        loaiMuBaoHiemTen: 'Nón Full Face',
        nhaSanXuatId: 1,
        nhaSanXuatTen: 'Royal',
        mauSacId: 1,
        mauSacTen: 'Đen',
        chatLieuVoId: 1,
        chatLieuVoTen: 'ABS',
        trongLuongId: 1,
        trongLuongTen: '1.5kg',
        xuatXuId: 1,
        xuatXuTen: 'Việt Nam',
        kieuDangMuId: 1,
        kieuDangMuTen: 'Thể thao',
        congNgheAnToanId: 1,
        congNgheAnToanTen: 'DOT'
      },
      {
        id: 2,
        tenSanPham: 'Royal M08 V.1 Modular',
        maSanPham: 'ROYAL-M08',
        giaBan: 1050000,
        soLuongTon: 30,
        moTa: 'Mũ bảo hiểm modular với thiết kế hiện đại',
        trangThai: true,
        ngayTao: new Date().toISOString(),
        anhSanPham: '/assets/default-product.png',
        loaiMuBaoHiemId: 3,
        loaiMuBaoHiemTen: 'Nón lật cằm',
        nhaSanXuatId: 1,
        nhaSanXuatTen: 'Royal',
        mauSacId: 2,
        mauSacTen: 'Đỏ',
        chatLieuVoId: 1,
        chatLieuVoTen: 'ABS',
        trongLuongId: 1,
        trongLuongTen: '1.6kg',
        xuatXuId: 1,
        xuatXuTen: 'Việt Nam',
        kieuDangMuId: 2,
        kieuDangMuTen: 'Cổ điển',
        congNgheAnToanId: 1,
        congNgheAnToanTen: 'DOT'
      },
      {
        id: 3,
        tenSanPham: 'Royal RACE FULL Black',
        maSanPham: 'ROYAL-RACE',
        giaBan: 1200000,
        soLuongTon: 25,
        moTa: 'Mũ bảo hiểm full face thể thao',
        trangThai: true,
        ngayTao: new Date().toISOString(),
        anhSanPham: '/assets/default-product.png',
        loaiMuBaoHiemId: 2,
        loaiMuBaoHiemTen: 'Nón Full Face',
        nhaSanXuatId: 1,
        nhaSanXuatTen: 'Royal',
        mauSacId: 1,
        mauSacTen: 'Đen',
        chatLieuVoId: 2,
        chatLieuVoTen: 'Carbon',
        trongLuongId: 2,
        trongLuongTen: '1.3kg',
        xuatXuId: 1,
        xuatXuTen: 'Việt Nam',
        kieuDangMuId: 1,
        kieuDangMuTen: 'Thể thao',
        congNgheAnToanId: 2,
        congNgheAnToanTen: 'ECE'
      },
      {
        id: 4,
        tenSanPham: 'Royal SPEED C White',
        maSanPham: 'ROYAL-SPEED',
        giaBan: 950000,
        soLuongTon: 40,
        moTa: 'Mũ bảo hiểm full face với thiết kế thể thao',
        trangThai: true,
        ngayTao: new Date().toISOString(),
        anhSanPham: '/assets/default-product.png',
        loaiMuBaoHiemId: 2,
        loaiMuBaoHiemTen: 'Nón Full Face',
        nhaSanXuatId: 1,
        nhaSanXuatTen: 'Royal',
        mauSacId: 3,
        mauSacTen: 'Trắng',
        chatLieuVoId: 1,
        chatLieuVoTen: 'ABS',
        trongLuongId: 1,
        trongLuongTen: '1.5kg',
        xuatXuId: 1,
        xuatXuTen: 'Việt Nam',
        kieuDangMuId: 1,
        kieuDangMuTen: 'Thể thao',
        congNgheAnToanId: 1,
        congNgheAnToanTen: 'DOT'
      },
      {
        id: 5,
        tenSanPham: 'Royal M137 Modular Yellow',
        maSanPham: 'ROYAL-M137',
        giaBan: 1350000,
        soLuongTon: 20,
        moTa: 'Mũ bảo hiểm modular với màu vàng nổi bật',
        trangThai: true,
        ngayTao: new Date().toISOString(),
        anhSanPham: '/assets/default-product.png',
        loaiMuBaoHiemId: 3,
        loaiMuBaoHiemTen: 'Nón lật cằm',
        nhaSanXuatId: 1,
        nhaSanXuatTen: 'Royal',
        mauSacId: 4,
        mauSacTen: 'Vàng',
        chatLieuVoId: 1,
        chatLieuVoTen: 'ABS',
        trongLuongId: 1,
        trongLuongTen: '1.6kg',
        xuatXuId: 1,
        xuatXuTen: 'Việt Nam',
        kieuDangMuId: 2,
        kieuDangMuTen: 'Cổ điển',
        congNgheAnToanId: 1,
        congNgheAnToanTen: 'DOT'
      },
      {
        id: 6,
        tenSanPham: 'Royal 3/4 Classic Black',
        maSanPham: 'ROYAL-34',
        giaBan: 590000,
        soLuongTon: 60,
        moTa: 'Mũ bảo hiểm 3/4 cổ điển',
        trangThai: true,
        ngayTao: new Date().toISOString(),
        anhSanPham: '/assets/default-product.png',
        loaiMuBaoHiemId: 1,
        loaiMuBaoHiemTen: 'Nón 3/4',
        nhaSanXuatId: 1,
        nhaSanXuatTen: 'Royal',
        mauSacId: 1,
        mauSacTen: 'Đen',
        chatLieuVoId: 1,
        chatLieuVoTen: 'ABS',
        trongLuongId: 1,
        trongLuongTen: '1.2kg',
        xuatXuId: 1,
        xuatXuTen: 'Việt Nam',
        kieuDangMuId: 2,
        kieuDangMuTen: 'Cổ điển',
        congNgheAnToanId: 1,
        congNgheAnToanTen: 'DOT'
      },
      {
        id: 7,
        tenSanPham: 'Royal Carbon Pro',
        maSanPham: 'ROYAL-CARBON',
        giaBan: 2950000,
        soLuongTon: 15,
        moTa: 'Mũ bảo hiểm carbon cao cấp',
        trangThai: true,
        ngayTao: new Date().toISOString(),
        anhSanPham: '/assets/default-product.png',
        loaiMuBaoHiemId: 5,
        loaiMuBaoHiemTen: 'Nón Carbon',
        nhaSanXuatId: 1,
        nhaSanXuatTen: 'Royal',
        mauSacId: 1,
        mauSacTen: 'Đen',
        chatLieuVoId: 2,
        chatLieuVoTen: 'Carbon',
        trongLuongId: 2,
        trongLuongTen: '1.1kg',
        xuatXuId: 1,
        xuatXuTen: 'Việt Nam',
        kieuDangMuId: 1,
        kieuDangMuTen: 'Thể thao',
        congNgheAnToanId: 2,
        congNgheAnToanTen: 'ECE'
      },
      {
        id: 8,
        tenSanPham: 'Royal Kids Blue',
        maSanPham: 'ROYAL-KIDS',
        giaBan: 450000,
        soLuongTon: 35,
        moTa: 'Mũ bảo hiểm dành cho trẻ em',
        trangThai: true,
        ngayTao: new Date().toISOString(),
        anhSanPham: '/assets/default-product.png',
        loaiMuBaoHiemId: 4,
        loaiMuBaoHiemTen: 'Nón trẻ em',
        nhaSanXuatId: 1,
        nhaSanXuatTen: 'Royal',
        mauSacId: 5,
        mauSacTen: 'Xanh',
        chatLieuVoId: 1,
        chatLieuVoTen: 'ABS',
        trongLuongId: 3,
        trongLuongTen: '0.9kg',
        xuatXuId: 1,
        xuatXuTen: 'Việt Nam',
        kieuDangMuId: 3,
        kieuDangMuTen: 'Trẻ em',
        congNgheAnToanId: 1,
        congNgheAnToanTen: 'DOT'
      },
      {
        id: 9,
        tenSanPham: 'Kính Bubble',
        maSanPham: 'KINH-BUBBLE',
        giaBan: 180000,
        soLuongTon: 100,
        moTa: 'Kính bảo vệ mắt kiểu bubble',
        trangThai: true,
        ngayTao: new Date().toISOString(),
        anhSanPham: '/assets/default-product.png',
        loaiMuBaoHiemId: 6,
        loaiMuBaoHiemTen: 'Phụ kiện',
        nhaSanXuatId: 2,
        nhaSanXuatTen: 'Accessories Pro',
        mauSacId: 6,
        mauSacTen: 'Trong suốt',
        chatLieuVoId: 3,
        chatLieuVoTen: 'Polycarbonate',
        trongLuongId: 4,
        trongLuongTen: '0.1kg',
        xuatXuId: 1,
        xuatXuTen: 'Việt Nam',
        kieuDangMuId: 4,
        kieuDangMuTen: 'Phụ kiện',
        congNgheAnToanId: 1,
        congNgheAnToanTen: 'CE'
      },
      {
        id: 10,
        tenSanPham: 'Kính dây',
        maSanPham: 'KINH-DAY',
        giaBan: 100000,
        soLuongTon: 150,
        moTa: 'Kính bảo vệ mắt có dây đeo',
        trangThai: true,
        ngayTao: new Date().toISOString(),
        anhSanPham: '/assets/default-product.png',
        loaiMuBaoHiemId: 6,
        loaiMuBaoHiemTen: 'Phụ kiện',
        nhaSanXuatId: 2,
        nhaSanXuatTen: 'Accessories Pro',
        mauSacId: 6,
        mauSacTen: 'Trong suốt',
        chatLieuVoId: 3,
        chatLieuVoTen: 'Polycarbonate',
        trongLuongId: 4,
        trongLuongTen: '0.1kg',
        xuatXuId: 1,
        xuatXuTen: 'Việt Nam',
        kieuDangMuId: 4,
        kieuDangMuTen: 'Phụ kiện',
        congNgheAnToanId: 1,
        congNgheAnToanTen: 'CE'
      },
      {
        id: 11,
        tenSanPham: 'Kính mặt nạ',
        maSanPham: 'KINH-MAT-NA',
        giaBan: 350000,
        soLuongTon: 80,
        moTa: 'Kính mặt nạ bảo vệ toàn diện',
        trangThai: true,
        ngayTao: new Date().toISOString(),
        anhSanPham: '/assets/default-product.png',
        loaiMuBaoHiemId: 6,
        loaiMuBaoHiemTen: 'Phụ kiện',
        nhaSanXuatId: 2,
        nhaSanXuatTen: 'Accessories Pro',
        mauSacId: 1,
        mauSacTen: 'Đen',
        chatLieuVoId: 3,
        chatLieuVoTen: 'Polycarbonate',
        trongLuongId: 4,
        trongLuongTen: '0.15kg',
        xuatXuId: 1,
        xuatXuTen: 'Việt Nam',
        kieuDangMuId: 4,
        kieuDangMuTen: 'Phụ kiện',
        congNgheAnToanId: 1,
        congNgheAnToanTen: 'CE'
      },
      {
        id: 12,
        tenSanPham: 'Royal Full Face Red',
        maSanPham: 'ROYAL-FF-RED',
        giaBan: 780000,
        soLuongTon: 45,
        moTa: 'Mũ bảo hiểm full face màu đỏ',
        trangThai: true,
        ngayTao: new Date().toISOString(),
        anhSanPham: '/assets/default-product.png',
        loaiMuBaoHiemId: 2,
        loaiMuBaoHiemTen: 'Nón Full Face',
        nhaSanXuatId: 1,
        nhaSanXuatTen: 'Royal',
        mauSacId: 2,
        mauSacTen: 'Đỏ',
        chatLieuVoId: 1,
        chatLieuVoTen: 'ABS',
        trongLuongId: 1,
        trongLuongTen: '1.5kg',
        xuatXuId: 1,
        xuatXuTen: 'Việt Nam',
        kieuDangMuId: 1,
        kieuDangMuTen: 'Thể thao',
        congNgheAnToanId: 1,
        congNgheAnToanTen: 'DOT'
      }
    ];
  }
}

